title: SeeSharpRun.NET
email: info@seesharprun.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://seesharprun.net"
twitter_username: sidney_andrews
github_username:  seesharprun
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
sass:
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock