pool:
  vmImage: 'Ubuntu 16.04'
steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  displayName: 'Get Ruby 2.4'
- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'Install Bundle'
- script: |
    bundle exec jekyll build -d $(Build.ArtifactStagingDirectory)
  displayName: 'Execute Bundle'  
- task: PublishBuildArtifacts@1
  displayName: 'Publish site artifacts'
  inputs:
    ArtifactName: site